config/routes.rb
Rails.application.routes.draw do
  resources :albums
  devise_for :users
  root to: 'albums#fetch_artists'
  get '/artists', to: 'albums#fetch_artists', as: :artists
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user

  validates :album_name, presence: true, uniqueness: true
  validates :year, presence: true,
                   format: { with: /(19|20)\d{2}/i },
                   numericality: {
                     only_integer: true,
                     greater_than_or_equal_to: 1900,
                     less_than_or_equal_to: Date.today.year
                   }
  validates :album_name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %I[user admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, authentication_keys: %I[username]
  validates :username, presence: true, uniqueness: true
  validates :full_name, presence: true, uniqueness: true
  validates :role, presence: true
  has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
require 'open-uri'
require 'json'
require 'rest-client'

OpenURI::Buffer.send :remove_const, 'StringMax' if OpenURI::Buffer.const_defined?('StringMax')
OpenURI::Buffer.const_set 'StringMax', 0

class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show edit update destroy]
  before_action :fetch_artist_names, only: %i[new create edit update]

  def index
    @albums = Album.all
  end

  def show
  end

  def new
    @album = Album.new
  end

  def edit
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.admin?
      @album.destroy
      respond_to do |format|
        format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
        format.json { head :no_content }
    end
    else
      respond_to do |format|
        format.html { redirect_to @album, notice: 'Only Admins users can destroy Albums.' }
        format.json { head :unauthorized }
      end
    end
  end

  def fetch_artists
    response = RestClient.get ENV['MOAT_API'], { Basic: ENV['MOAT_HEADERS'] }
    @artists = JSON.parse(response.body).flatten
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:album_name, :year, :artist_name, :user_id)
  end

  def fetch_artist_names
    response = RestClient.get ENV['MOAT_API'], { Basic: ENV['MOAT_HEADERS'] }
    results = JSON.parse(response.body).flatten
    @artist_names = []
    results.each do |result|
      @artist_names << result["name"]
    end
    @artist_names
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_admin, :set_user
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %I[username full_name role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %I[username full_name role])
  end

  def set_admin
    return create_adminuser unless User.find_by(username: "admin")
  end

  def set_user
    return create_user unless User.find_by(username: "user")
  end

  private

  def create_adminuser
    case Rails.env
    when "development"
      User.create!(username: "admin", full_name: "admin", password: "123456", role: :admin)
    when "production"
      User.create(username: "admin", full_name: "admin", password: "123456", role: :admin)
    end
  end

  def create_user
    case Rails.env
    when "development"
      User.create!(username: "user", full_name: "user", password: "123456", role: :user)
    when "production"
      User.create(username: "user", full_name: "user", password: "123456", role: :user)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :album_name %>
    <%= f.input :year %>
    <%= f.input :artist_name, collection: @artist_names, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 offset-lg-3">
      <div class="m-5">
        <h2 class="text-center mb-5">Editing Album</h2>
        <%= render 'form', album: @album %>
        <%= link_to 'Show', @album %> |
        <%= link_to 'Back', albums_path %>
      </div>  
    </div>
  </div>
</div>

app/views/albums/fetch_artists.html.erb
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>

<div class="container-lg my">
  <h1>Artists</h1>
  <div class="cards">
    <% @artists.each do |artist| %>
      <div class="grid-card">
        <div class="card-product-infos">
          <div>
            <h3><%= artist["name"] %></h3>
            <p>Twitter: <%= artist["twitter"] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Albums', albums_path %>
</div>

app/views/albums/get_artists.html.erb
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>

<div class="container-lg my">
  <h1>Artists</h1>
  <div class="cards">
    <% @artists.each do |artist| %>
      <div class="grid-card">
        <div class="card-product-infos">
          <div>
            <h3><%= artist["name"] %></h3>
            <p>Twitter: <%= artist["twitter"] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Albums', albums_path %>
</div>

app/views/albums/index.html.erb
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>

<div class="container-lg my">
  <h1>Albums</h1>
  <div class="cards">
    <% @albums.each do |album| %>
      <div class="grid-card">
        <div class="card-product-infos">
          <div>
            <h3><%= link_to album.album_name.capitalize, album_path(album) %></h5>
            <p>Year: <%= album.year %></p>
            <p>Artist: <%= album.artist_name %></p>
          </div>
          <div>
            <%= link_to 'Show', album %>
            <%= link_to 'Edit', edit_album_path(album) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'New Album', new_album_path %>
</div>

            
          

app/views/albums/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 offset-lg-3">
      <div class="m-5">
        <h2 class="text-center mb-5">New album</h2>
        <%= render 'form', album: @album %>
        <%= link_to 'Back', albums_path %>
      </div>  
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 offset-lg-3">
      <div class="m-5">
        <p>
          <strong>Album name:</strong>
          <%= @album.album_name %>
        </p>

        <p>
          <strong>Year:</strong>
          <%= @album.year %>
        </p>

        <p>
          <strong>Artist:</strong>
          <%= @album.artist_name %>
        </p>

        <%= link_to 'Edit', edit_album_path(@album) %> |
        <%= link_to 'Back', albums_path %> |
        <% if current_user.role == "admin" %>
              <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>  
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicCollectionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        </li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>